In [29]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import warnings
warnings.filterwarnings('ignore')
import seaborn

# feature extraction

## `collected_data`

In [30]:
collected_data = pd.read_csv("../data/data_d_final/2d201_1230_collected_data.csv")
collected_data.set_index("지역", inplace=True)
collected_data

쏘카존 수        녹지        주거        공업        상업      인구  대학교 수  아파트 수  \
지역                                                                              
가평군           7  1.000000  0.000000  0.000000  0.000000   62197      1     39   
고양시 덕양구      48  0.656250  0.343750  0.000000  0.000000  487874      6    274   
고양시 일산동구     51  0.461538  0.461538  0.000000  0.076923  296590      1    133   
고양시 일산서구     29  0.500000  0.375000  0.000000  0.125000  290738      0    140   
과천시           3  0.500000  0.500000  0.000000  0.000000   77775      1     15   
광명시          28  0.222222  0.666667  0.000000  0.111111  288182      0     89   
광주시          16  0.923077  0.076923  0.000000  0.000000  391704     11    129   
구리시          19  0.500000  0.500000  0.000000  0.000000  188876      0    111   
군포시          10  0.333333  0.444444  0.222222  0.000000  266531      7    155   
김포시          55  0.400000  0.533333  0.066667  0.000000  484194      3    229   
남양주시         57  0.526316  0.473684  0.000000  0.000000  737366      2    385   
동두천시          4  0.750000  0.083333  0.083333  0.083333   91735      3     41   
부천시          57  0.230769  0.615385  0.153846  0.000000  791263     14    520   
성남시 분당구      58  0.500000  0.500000  0.000000  0.000000  482026      1    231   
성남시 수정구      18  0.631579  0.368421  0.000000  0.000000  232125     11     91   
성남시 중원구      13  0.555556  0.222222  0.111111  0.111111  206211      1     79   
수원시 권선구      16  0.625000  0.312500  0.062500  0.000000  367004      1    159   
수원시 영통구      34  0.142857  0.571429  0.285714  0.000000  360127     21    129   
수원시 장안구      18  0.272727  0.727273  0.000000  0.000000  271012      4    200   
수원시 팔달구      20  0.136364  0.409091  0.000000  0.454545  192225      0     65   
시흥시          35  0.774194  0.193548  0.032258  0.000000  512438      5    313   
안산시 단원구      25  0.428571  0.357143  0.214286  0.000000  297509      2    160   
안산시 상록구      21  0.666667  0.333333  0.000000  0.000000  345535      4     65   
안성시          13  0.555556  0.288889  0.044444  0.111111  189146     12     96   
안양시 동안구      19  0.250000  0.750000  0.000000  0.000000  314102      1    174   
안양시 만안구      19  0.666667  0.333333  0.000000  0.000000  234296     15    138   
양주시          12  0.727273  0.227273  0.045455  0.000000  241346      4    124   
양평군           5  1.000000  0.000000  0.000000  0.000000  122463      7     39   
여주시           7  0.875000  0.125000  0.000000  0.000000  113096      1     70   
연천군           3  1.000000  0.000000  0.000000  0.000000   42153      0     35   
오산시          15  0.333333  0.500000  0.083333  0.083333  229833      5     93   
용인시 기흥구      37  0.727273  0.181818  0.090909  0.000000  438500     16    251   
용인시 수지구      37  0.428571  0.571429  0.000000  0.000000  377198      9    214   
용인시 처인구      29  0.823529  0.058824  0.000000  0.117647  259872     15    112   
의왕시           5  0.636364  0.363636  0.000000  0.000000  160464      1    102   
의정부시         37  0.461538  0.461538  0.000000  0.076923  463789      6    299   
이천시          14  0.880000  0.080000  0.000000  0.040000  223151      4    155   
파주시          36  0.800000  0.142857  0.028571  0.028571  494970      2    221   
평택시          53  0.594595  0.270270  0.081081  0.054054  577335      9    367   
포천시           9  0.888889  0.111111  0.000000  0.000000  147019     15     76   
하남시          29  0.458333  0.541667  0.000000  0.000000  325310      0    131   
화성시          56  0.567568  0.351351  0.054054  0.027027  907958     27    388   

          지하철역 수  정류장 수  환승역 수  
지역                              
가평군            4    928      0  
고양시 덕양구        9   1205      2  
고양시 일산동구       6    454      0  
고양시 일산서구       4    635      0  
과천시            5    111      0  
광명시            3    445      0  
광주시            4   1238      0  
구리시            2    313      0  
군포시            7    438      2  
김포시            9   1325      0  
남양주시          13   1803      0  
동두천시           5

## `hackathon_data`

In [31]:
hackathon_data_original = pd.read_csv("../data/20211022_수요예측_hackathon_data.csv", encoding='cp949')
hackathon_data_original

region1   region2      reservation_return_at  \
0        울산광역시        남구  2019-09-29 21:25:40+00:00   
1        울산광역시        남구  2019-07-13 13:11:21+00:00   
2        울산광역시        남구  2019-09-16 23:43:08+00:00   
3        울산광역시        남구  2019-08-09 06:17:41+00:00   
4        울산광역시        남구  2019-07-24 12:36:29+00:00   
...        ...       ...                        ...   
457062     경기도  고양시　일산서구  2019-09-14 12:25:29+00:00   
457063     경기도  고양시　일산서구  2019-07-25 15:30:00+00:00   
457064     경기도  고양시　일산서구  2019-07-14 22:38:09+00:00   
457065     경기도  고양시　일산서구  2019-06-20 18:25:37+00:00   
457066     경기도  고양시　일산서구  2019-02-09 16:18:14+00:00   

             reservation_start_at  age_group   gender car_model  
0       2019-09-29 19:20:00+00:00          1     male        경형  
1       2019-07-13 11:00:00+00:00          1     male       준중형  
2       2019-09-16 19:10:00+00:00          1     male       준중형  
3       2019-08-09 00:20:00+00:00          1     male       준중형  
4       2019-07-24 09:00:00+00:00          2     male        경형  
...                           ...        ...      ...       ...  
457062  2019-09-14 12:00:00+00:00          1     male        경형  
457063  2019-07-24 18:30:00+00:00          4   female       준중형  
457064  2019-07-14 21:30:00+00:00          1     male        경형  
457065  2019-06-20 18:10:00+00:00          1  unknown     소형SUV  
457066  2019-02-09 12:40:00+00:00          3     male        중형  

[457067 rows x 7 columns]

In [32]:
# regions from hackathon data
regions_h= ['남구', '동구', '북구', '중구', '강서구', '광명시', '구리시', '김포시', '세종시', '양평군',
           '울주군', '하남시', '화성시', '남양주시', '의정부시', '고양시 덕양구',
           '성남시 분당구', '성남시 수정구', '성남시 중원구', '안양시 동안구',
           '안양시 만안구', '전주시 덕진구', '전주시 완산구', '고양시 일산동구', '고양시 일산서구']
D = dict(zip(hackathon_data_original['region2'].unique(),regions_h))
hackathon_data_original['region2'] = hackathon_data_original['region2'].map(D)
hackathon_data = pd.DataFrame(hackathon_data_original['region2'].value_counts())
hackathon_data.columns = ['이용수']
hackathon_data

이용수
성남시 분당구   46782
화성시       35249
고양시 일산동구  31906
남양주시      26546
고양시 덕양구   26253
의정부시      25225
안양시 동안구   22918
광명시       22645
남구        21836
김포시       21500
성남시 수정구   18773
안양시 만안구   16806
성남시 중원구   16238
고양시 일산서구  16052
세종시       15263
전주시 완산구   15013
울주군       13632
하남시       13456
구리시       13011
전주시 덕진구   12707
강서구       10634
동구         4526
북구         3799
중구         3310
양평군        2987

## intersected

In [33]:
intersected_rows = set.intersection(set(collected_data.index), set(hackathon_data.index))
intersected_rows = list(intersected_rows)
intersected_rows

['하남시',
 '화성시',
 '안양시 만안구',
 '고양시 일산서구',
 '남양주시',
 '의정부시',
 '김포시',
 '고양시 덕양구',
 '광명시',
 '구리시',
 '안양시 동안구',
 '양평군',
 '성남시 분당구',
 '성남시 수정구',
 '성남시 중원구',
 '고양시 일산동구']

In [34]:
collected_data_intersected = collected_data[collected_data.index.isin(intersected_rows)]
collected_data_intersected.sort_index(ascending=True, inplace=True)
hackathon_data_intersected = hackathon_data[hackathon_data.index.isin(intersected_rows)]
hackathon_data_intersected.sort_index(ascending=True, inplace=True)
intersected = pd.concat([collected_data_intersected, hackathon_data_intersected],axis=1)
intersected['쏘카존수 대비 이용수'] = intersected['이용수']/intersected['쏘카존 수']
intersected

쏘카존 수        녹지        주거        공업        상업      인구  대학교 수  아파트 수  \
고양시 덕양구      48  0.656250  0.343750  0.000000  0.000000  487874      6    274   
고양시 일산동구     51  0.461538  0.461538  0.000000  0.076923  296590      1    133   
고양시 일산서구     29  0.500000  0.375000  0.000000  0.125000  290738      0    140   
광명시          28  0.222222  0.666667  0.000000  0.111111  288182      0     89   
구리시          19  0.500000  0.500000  0.000000  0.000000  188876      0    111   
김포시          55  0.400000  0.533333  0.066667  0.000000  484194      3    229   
남양주시         57  0.526316  0.473684  0.000000  0.000000  737366      2    385   
성남시 분당구      58  0.500000  0.500000  0.000000  0.000000  482026      1    231   
성남시 수정구      18  0.631579  0.368421  0.000000  0.000000  232125     11     91   
성남시 중원구      13  0.555556  0.222222  0.111111  0.111111  206211      1     79   
안양시 동안구      19  0.250000  0.750000  0.000000  0.000000  314102      1    174   
안양시 만안구      19  0.666667  0.333333  0.000000  0.000000  234296     15    138   
양평군           5  1.000000  0.000000  0.000000  0.000000  122463      7     39   
의정부시         37  0.461538  0.461538  0.000000  0.076923  463789      6    299   
하남시          29  0.458333  0.541667  0.000000  0.000000  325310      0    131   
화성시          56  0.567568  0.351351  0.054054  0.027027  907958     27    388   

          지하철역 수  정류장 수  환승역 수    이용수  쏘카존수 대비 이용수  
고양시 덕양구        9   1205      2  26253   546.937500  
고양시 일산동구       6    454      0  31906   625.607843  
고양시 일산서구       4    635      0  16052   553.517241  
광명시            3    445      0  22645   808.750000  
구리시            2    313      0  13011   684.789474  
김포시            9   1325      0  21500   390.909091  
남양주시          13   1803      0  26546   465.719298  
성남시 분당구       12    694      3  46782   806.586207  
성남시 수정구        9    436      2  18773  1042.944444  
성남시 중원구        1    251      0  16238  1249.076923  
안양시 동안구        3    381      0  22918  1206.210526  
안양시 만안구        4    362      0  16806   884.526316  
양평군            9   1051      0   2987   597.400000  
의정부시          21    716      0  25225   681.756757  
하남시            4    581      0  13456   464.000000  
화성시            3   2873      2  35249   629.446429

## pearson correlation

In [35]:
intersected.corr()

쏘카존 수        녹지        주거        공업        상업        인구  \
쏘카존 수        1.000000 -0.275398  0.305132  0.033706 -0.106532  0.812603   
녹지          -0.275398  1.000000 -0.931103 -0.022967 -0.313009 -0.154536   
주거           0.305132 -0.931103  1.000000 -0.237979 -0.008059  0.175273   
공업           0.033706 -0.022967 -0.237979  1.000000  0.255624  0.159010   
상업          -0.106532 -0.313009 -0.008059  0.255624  1.000000 -0.169417   
인구           0.812603 -0.154536  0.175273  0.159010 -0.169417  1.000000   
대학교 수        0.112405  0.393989 -0.366502  0.164733 -0.242572  0.466642   
아파트 수        0.791505 -0.142347  0.196848  0.048032 -0.215756  0.950637   
지하철역 수       0.380477  0.155343 -0.060330 -0.289476 -0.155862  0.300060   
정류장 수        0.598342  0.197761 -0.176481  0.220930 -0.242405  0.875202   
환승역 수        0.410081  0.185389 -0.090934 -0.043676 -0.323283  0.400453   
이용수          0.806230 -0.369392  0.381949 -0.004037 -0.011755  0.649762   
쏘카존수 대비 이용수 -0.537069 -0.148646  0.060353  0.237283  0.166735 -0.390717   

                대학교 수     아파트 수    지하철역 수     정류장 수     환승역 수       이용수  \
쏘카존 수        0.112405  0.791505  0.380477  0.598342  0.410081  0.806230   
녹지           0.393989 -0.142347  0.155343  0.197761  0.185389 -0.369392   
주거          -0.366502  0.196848 -0.060330 -0.176481 -0.090934  0.381949   
공업           0.164733  0.048032 -0.289476  0.220930 -0.043676 -0.004037   
상업          -0.242572 -0.215756 -0.155862 -0.242405 -0.323283 -0.011755   
인구           0.466642  0.950637  0.300060  0.875202  0.400453  0.649762   
대학교 수        1.000000  0.382193 -0.015686  0.627799  0.401665  0.153327   
아파트 수        0.382193  1.000000  0.467030  0.771214  0.332206  0.623385   
지하철역 수      -0.015686  0.467030  1.000000  0.171590  0.185562  0.286200   
정류장 수        0.627799  0.771214  0.171590  1.000000  0.328058  0.335510   
환승역 수        0.401665  0.332206  0.185562  0.328058  1.000000  0.637355   
이용수          0.153327  0.623385  0.286200  0.335510  0.637355  1.000000   
쏘카존수 대비 이용수  0.012843 -0.388349 -0.312177 -0.491441  0.078405 -0.012417   

             쏘카존수 대비 이용수  
쏘카존 수          -0.537069  
녹지             -0.148646  
주거              0.060353  
공업              0.237283  
상업              0.166735  
인구             -0.390717  
대학교 수           0.012843  
아파트 수          -0.388349  
지하철역 수         -0.312177  
정류장 수          -0.491441  
환승역 수           0.078405  
이용수            -0.012417  
쏘카존수 대비 이용수     1.000000

In [43]:
X = np.array(collected_data.drop(columns=['대학교 수']))

# Clustering

## K=2

In [56]:
clusterer = KMeans(n_clusters=2, n_init="auto")
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0])

In [57]:
regions = np.array(collected_data.index)
print("군집0 : ", regions[np.where(cluster_labels==0)])
print()
print("군집1 : ", regions[np.where(cluster_labels==1)])

군집0 :  ['고양시 덕양구' '김포시' '남양주시' '부천시' '성남시 분당구' '시흥시' '용인시 기흥구' '의정부시' '파주시' '평택시'
 '화성시']

군집1 :  ['가평군' '고양시 일산동구' '고양시 일산서구' '과천시' '광명시' '광주시' '구리시' '군포시' '동두천시'
 '성남시 수정구' '성남시 중원구' '수원시 권선구' '수원시 영통구' '수원시 장안구' '수원시 팔달구' '안산시 단원구'
 '안산시 상록구' '안성시' '안양시 동안구' '안양시 만안구' '양주시' '양평군' '여주시' '연천군' '오산시'
 '용인시 수지구' '용인시 처인구' '의왕시' '이천시' '포천시' '하남시']


## K=3

In [58]:
clusterer = KMeans(n_clusters=3, n_init="auto")
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 2, 1, 2, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 2])

In [59]:
regions = np.array(collected_data.index)
print("군집0 : ", regions[np.where(cluster_labels==0)])
print()
print("군집1 : ", regions[np.where(cluster_labels==1)])
print()
print("군집2 : ", regions[np.where(cluster_labels==2)])

군집0 :  ['고양시 덕양구' '광주시' '김포시' '성남시 분당구' '수원시 권선구' '수원시 영통구' '시흥시' '안산시 상록구'
 '용인시 기흥구' '용인시 수지구' '의정부시' '파주시' '평택시']

군집1 :  ['가평군' '고양시 일산동구' '고양시 일산서구' '과천시' '광명시' '구리시' '군포시' '동두천시' '성남시 수정구'
 '성남시 중원구' '수원시 장안구' '수원시 팔달구' '안산시 단원구' '안성시' '안양시 동안구' '안양시 만안구' '양주시'
 '양평군' '여주시' '연천군' '오산시' '용인시 처인구' '의왕시' '이천시' '포천시' '하남시']

군집2 :  ['남양주시' '부천시' '화성시']


## K=4

In [60]:
clusterer = KMeans(n_clusters=4, n_init="auto")
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([1, 0, 3, 3, 1, 3, 0, 1, 3, 0, 2, 1, 2, 0, 3, 3, 3, 3, 3, 1, 0, 3,
       3, 1, 3, 3, 3, 1, 1, 1, 3, 0, 0, 3, 1, 0, 3, 0, 0, 1, 3, 2])

In [61]:
regions = np.array(collected_data.index)
print("군집0 : ", regions[np.where(cluster_labels==0)])
print()
print("군집1 : ", regions[np.where(cluster_labels==1)])
print()
print("군집2 : ", regions[np.where(cluster_labels==2)])
print()
print("군집3 : ", regions[np.where(cluster_labels==3)])

군집0 :  ['고양시 덕양구' '광주시' '김포시' '성남시 분당구' '시흥시' '용인시 기흥구' '용인시 수지구' '의정부시' '파주시'
 '평택시']

군집1 :  ['가평군' '과천시' '구리시' '동두천시' '수원시 팔달구' '안성시' '양평군' '여주시' '연천군' '의왕시' '포천시']

군집2 :  ['남양주시' '부천시' '화성시']

군집3 :  ['고양시 일산동구' '고양시 일산서구' '광명시' '군포시' '성남시 수정구' '성남시 중원구' '수원시 권선구' '수원시 영통구'
 '수원시 장안구' '안산시 단원구' '안산시 상록구' '안양시 동안구' '안양시 만안구' '양주시' '오산시' '용인시 처인구'
 '이천시' '하남시']


## K=5

In [63]:
clusterer = KMeans(n_clusters=5, n_init="auto")
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([1, 0, 4, 4, 1, 4, 4, 3, 3, 0, 2, 1, 2, 0, 3, 3, 4, 4, 3, 3, 0, 4,
       4, 3, 4, 3, 3, 1, 1, 1, 3, 0, 4, 3, 1, 0, 3, 0, 0, 1, 4, 2])

In [64]:
regions = np.array(collected_data.index)
print("군집0 : ", regions[np.where(cluster_labels==0)])
print()
print("군집1 : ", regions[np.where(cluster_labels==1)])
print()
print("군집2 : ", regions[np.where(cluster_labels==2)])
print()
print("군집3 : ", regions[np.where(cluster_labels==3)])
print()
print("군집4 : ", regions[np.where(cluster_labels==4)])

군집0 :  ['고양시 덕양구' '김포시' '성남시 분당구' '시흥시' '용인시 기흥구' '의정부시' '파주시' '평택시']

군집1 :  ['가평군' '과천시' '동두천시' '양평군' '여주시' '연천군' '의왕시' '포천시']

군집2 :  ['남양주시' '부천시' '화성시']

군집3 :  ['구리시' '군포시' '성남시 수정구' '성남시 중원구' '수원시 장안구' '수원시 팔달구' '안성시' '안양시 만안구' '양주시'
 '오산시' '용인시 처인구' '이천시']

군집4 :  ['고양시 일산동구' '고양시 일산서구' '광명시' '광주시' '수원시 권선구' '수원시 영통구' '안산시 단원구' '안산시 상록구'
 '안양시 동안구' '용인시 수지구' '하남시']


## K=6

In [77]:
clusterer = KMeans(n_clusters=6, n_init="auto")
cluster_labels = clusterer.fit_predict(X)
cluster_labels

array([0, 1, 3, 3, 0, 3, 3, 4, 4, 1, 5, 0, 5, 1, 4, 4, 3, 3, 4, 4, 1, 3,
       3, 4, 3, 4, 4, 0, 0, 0, 4, 1, 3, 4, 0, 1, 4, 1, 1, 0, 3, 2])

In [69]:
regions = np.array(collected_data.index)
print("군집0 : ", regions[np.where(cluster_labels==0)])
print()
print("군집1 : ", regions[np.where(cluster_labels==1)])
print()
print("군집2 : ", regions[np.where(cluster_labels==2)])
print()
print("군집3 : ", regions[np.where(cluster_labels==3)])
print()
print("군집4 : ", regions[np.where(cluster_labels==4)])
print()
print("군집5 : ", regions[np.where(cluster_labels==5)])

군집0 :  ['고양시 덕양구' '김포시' '성남시 분당구' '시흥시' '용인시 기흥구' '의정부시' '파주시' '평택시']

군집1 :  ['구리시' '성남시 중원구' '수원시 팔달구' '안성시' '의왕시' '포천시']

군집2 :  ['남양주시' '부천시' '화성시']

군집3 :  ['고양시 일산동구' '고양시 일산서구' '광명시' '군포시' '성남시 수정구' '수원시 장안구' '안산시 단원구' '안양시 만안구'
 '양주시' '오산시' '용인시 처인구' '이천시']

군집4 :  ['광주시' '수원시 권선구' '수원시 영통구' '안산시 상록구' '안양시 동안구' '용인시 수지구' '하남시']

군집5 :  ['가평군' '과천시' '동두천시' '양평군' '여주시' '연천군']


시각화

In [85]:
import folium
import geopandas

In [88]:
#Import Libraries
import geopandas as gpd
import pandas as pd
import numpy as np
import folium
from folium.features import GeoJsonTooltip

#Read the geoJSON file using geopandas
geojson = gpd.read_file('georef-united-states-of-america-county.geojson')
geojson=geojson[['coty_code','geometry']] #only select 'coty_code' (country fips) and 'geometry' columns

#Read the covid-19 data using pandas
covid_df=pd.read_csv('United_States_COVID-19_County_Level.csv')


FileNotFoundError: [Errno 2] No such file or directory: 'United_States_COVID-19_County_Level.csv'

In [82]:
us_map = folium.Map(location=[40, -96], zoom_start=4,tiles='openstreetmap')
us_map

In [83]:
#Create the choropleth map add it to the base map
custom_scale = (df_final['new_cases_7days'].quantile((0,0.2,0.4,0.6,0.8,1))).tolist()
folium.Choropleth(
            geo_data=r'...\georef-united-states-of-america-county.geojson',
            data=df_final,
            columns=['fips_code', 'new_cases_7days'],  #Here we tell folium to get the county fips and plot new_cases_7days metric for each county
            key_on='feature.properties.coty_code', #Here we grab the geometries/county boundaries from the geojson file using the key 'coty_code' which is the same as county fips
            threshold_scale=custom_scale, #use the custom scale we created for legend
            fill_color='YlOrRd',
            nan_fill_color="White", #Use white color if there is no data available for the county
            fill_opacity=0.7,
            line_opacity=0.2,
            legend_name='New Cases Past 7 Days (Per 100K Population) ', #title of the legend
            highlight=True,
            line_color='black').add_to(us_map) 

us_map


NameError: name 'df_final' is not defined